niranjanmaradapu/PointOfSale

- new-sale-api/src/main/java/com/otsi/retail/newSale/NewSaleApiApplication.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/config/Config.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/controller/NewSaleController.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/HSNVoService.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleService.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/serviceimpl/NewSaleServiceImpl.java
> Update Tax field

- new-sale-api/src/main/java/com/otsi/retail/newSale/common/CommonRequestMappigs.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/controller/NewSaleController.java
- new-sale-api/src/main/resources/application.yml
kindly  review the pos day close
> implemented pos day close

- new-sale-api/src/main/java/com/otsi/retail/newSale/Entity/CustomerDetailsEntity.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/Entity/DeliverySlipEntity.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/Entity/NewSaleEntity.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/controller/NewSaleController.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/mapper/CustomerMapper.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/mapper/DeliverySlipMapper.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleService.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/serviceimpl/CustomerServiceImpl.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/serviceimpl/NewSaleServiceImpl.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/vo/CustomerVo.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/vo/NewSaleVo.java
Kindly review the chnages for validation
> Validations on New sale and Ds Slip

- new-sale-api/src/main/java/com/otsi/retail/newSale/Entity/GiftVoucherEntity.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/Entity/UserData.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/Entity/UserDataAv.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/common/UserDataAVEnum.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/controller/NewSaleController.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/repository/GiftVoucherRepo.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/repository/UserDataAvRepo.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/repository/UserDataRepo.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/CustomerService.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleService.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/serviceimpl/CustomerServiceImpl.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/serviceimpl/NewSaleServiceImpl.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/vo/GiftVoucherVo.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/vo/UserDataVo.java
Implemented tag customer to GV and Userdata and userdata av Tables
> Implemented tag customer to GV and Userdata and userdata av Tables

- connection-pool/pom.xml
- connection-pool/src/main/java/com/otsi/retail/connectionpool/common/CommonRequestMappigs.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/entity/PromotionsEntity.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/mapper/PromotionMapper.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/serviceImpl/PromotionServiceImpl.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/vo/PromotionsVo.java
- connection-pool/src/main/resources/application.yml
> Implemented the mapping from promotion to store api

- connection-pool/src/main/java/com/otsi/retail/connectionpool/common/CommonRequestMappigs.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/common/PromotionType.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/controller/StoreController.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/entity/PromotionsEntity.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/entity/StoresEntity.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/mapper/StoreMapper.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/repository/RuleRepo.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/repository/StoreRepo.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/service/StoresService.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/serviceImpl/StoresServiceImpl.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/vo/StoreVo.java
> added promotion-store api

- new-sale-api/src/main/java/com/otsi/retail/newSale/controller/NewSaleController.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/mapper/NewSaleMapper.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/HSNVoService.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleService.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleServiceImpl.java
impleented API for List of all Barcodes
> Implemented Get all Barcode items

- connection-pool/src/main/java/com/otsi/retail/connectionpool/controller/PoolController.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/controller/PromotionController.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/controller/StoreController.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/errors/ErrorResponse.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/exceptions/CustomExceptionHandler.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/exceptions/DuplicateRecordException.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/exceptions/EmptyInputException.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/exceptions/InvalidDataException.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/exceptions/RecordNotFoundException.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/service/PoolService.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/service/PoolServiceImpl.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/service/PromotionService.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/service/PromotionServiceImpl.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/service/StoresService.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/service/StoresServiceImpl.java
- connection-pool/src/main/resources/application.yml
- debit-notes/src/main/java/com/otsi/retail/debitnotes/errors/ErrorResponse.java
- debit-notes/src/main/java/com/otsi/retail/debitnotes/exceptions/CustomExceptionHandler.java
- debit-notes/src/main/java/com/otsi/retail/debitnotes/exceptions/DataNotFoundException.java
- debit-notes/src/main/java/com/otsi/retail/debitnotes/exceptions/RecordNotFoundException.java
- debit-notes/src/main/java/com/otsi/retail/debitnotes/gatewayresponse/GateWayResponse.java
- debit-notes/src/main/java/com/otsi/retail/debitnotes/service/DebitNotesService.java
- debit-notes/src/main/java/com/otsi/retail/debitnotes/service/DebitNotesServiceImpl.java
> added exception handling

- customer-management/src/main/java/com/otsi/retail/customerManagement/config/Config.java
- customer-management/src/main/java/com/otsi/retail/customerManagement/controller/CustomerController.java
- customer-management/src/main/java/com/otsi/retail/customerManagement/gatewayresponse/GateWayResponse.java
- customer-management/src/main/java/com/otsi/retail/customerManagement/repo/ReturnSlipRepo.java
- customer-management/src/main/java/com/otsi/retail/customerManagement/service/CustomerService.java
- customer-management/src/main/java/com/otsi/retail/customerManagement/service/CustomerServiceImpl.java
- customer-management/src/main/java/com/otsi/retail/customerManagement/service/HSNVoService.java
- customer-management/src/main/java/com/otsi/retail/customerManagement/vo/BarcodeVo.java
- customer-management/src/main/java/com/otsi/retail/customerManagement/vo/HsnDetailsVo.java
- customer-management/src/main/java/com/otsi/retail/customerManagement/vo/RetrnSlipDetailsVo.java
- customer-management/src/main/java/com/otsi/retail/customerManagement/vo/SlabVo.java
- customer-management/src/main/java/com/otsi/retail/customerManagement/vo/TaxVo.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/common/CommonRequestMappigs.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/controller/NewSaleController.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/mapper/NewSaleMapper.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleService.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleServiceImpl.java
> implementing get ReturnSlipDetails and update returnSlip

- customer-management/src/main/resources/application.yml
> added url's in yml file

- connection-pool/src/main/java/com/otsi/retail/connectionpool/controller/PoolController.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/controller/PromotionController.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/controller/StoreController.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/errors/ErrorResponse.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/exceptions/CustomExceptionHandler.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/gatewayresponse/GateWayResponse.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/service/PoolServiceImpl.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/service/PromotionServiceImpl.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/service/StoresServiceImpl.java
- debit-notes/src/main/java/com/otsi/retail/debitnotes/controller/DebitNotesController.java
- debit-notes/src/main/java/com/otsi/retail/debitnotes/errors/ErrorResponse.java
- debit-notes/src/main/java/com/otsi/retail/debitnotes/exceptions/CustomExceptionHandler.java
- debit-notes/src/main/java/com/otsi/retail/debitnotes/exceptions/DataNotFoundException.java
- debit-notes/src/main/java/com/otsi/retail/debitnotes/exceptions/InvalidDataException.java
- debit-notes/src/main/java/com/otsi/retail/debitnotes/gatewayresponse/GateWayResponse.java
- debit-notes/src/main/java/com/otsi/retail/debitnotes/service/DebitNotesServiceImpl.java
- debit-notes/src/main/resources/application.yml
> added exception handling and exception class

- new-sale-api/src/main/java/com/otsi/retail/newSale/Exceptions/CustomExceptionHandler.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/Exceptions/DataNotFoundException.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/Exceptions/DuplicateRecordException.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/Exceptions/InvalidInputException.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/controller/NewSaleController.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/errors/ErrorResponse.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/gatewayresponse/GateWayResponse.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/CustomerService.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/CustomerServiceImpl.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleService.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleServiceImpl.java
- user-store-mapping/src/main/java/com/otsi/retail/userStore/controller/StoreController.java
- user-store-mapping/src/main/java/com/otsi/retail/userStore/controller/UserController.java
- user-store-mapping/src/main/java/com/otsi/retail/userStore/errors/ErrorResponse.java
- user-store-mapping/src/main/java/com/otsi/retail/userStore/exceptions/CustomExceptionHandler.java
- user-store-mapping/src/main/java/com/otsi/retail/userStore/exceptions/DataNotFoundException.java
- user-store-mapping/src/main/java/com/otsi/retail/userStore/exceptions/RecordNotFoundException.java
- user-store-mapping/src/main/java/com/otsi/retail/userStore/gatewayresponse/GateWayResponse.java
- user-store-mapping/src/main/java/com/otsi/retail/userStore/service/StoreService.java
- user-store-mapping/src/main/java/com/otsi/retail/userStore/service/StoreServiceImp.java
- user-store-mapping/src/main/java/com/otsi/retail/userStore/service/UserServiceImp.java
> implemented exception handling

- connection-pool/src/main/java/com/otsi/retail/connectionpool/exceptions/CustomExceptionHandler.java
- customer-management/src/main/java/com/otsi/retail/customerManagement/CustomerManagementApplication.java
- customer-management/src/main/java/com/otsi/retail/customerManagement/controller/CustomerController.java
- customer-management/src/main/java/com/otsi/retail/customerManagement/controller/ReasonController.java
- customer-management/src/main/java/com/otsi/retail/customerManagement/exceptions/CustomExceptionHandler.java
- customer-management/src/main/java/com/otsi/retail/customerManagement/service/CustomerServiceImpl.java
- customer-management/src/main/java/com/otsi/retail/customerManagement/service/ReasonServiceImpl.java
- customer-management/src/main/resources/application.yml
- debit-notes/src/main/java/com/otsi/retail/debitnotes/exceptions/CustomExceptionHandler.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/Exceptions/CustomExceptionHandler.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/controller/NewSaleController.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/CustomerServiceImpl.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleServiceImpl.java
- promo-exchange/src/main/java/com/otsi/retail/promoexchange/controller/PromoExchangeController.java
- promo-exchange/src/main/java/com/otsi/retail/promoexchange/exceptions/CustomExceptionHandler.java
- promo-exchange/src/main/java/com/otsi/retail/promoexchange/service/CustomerServiceImpl.java
- promo-exchange/src/main/java/com/otsi/retail/promoexchange/service/PromoExchangeServiceeImpl.java
- user-store-mapping/src/main/java/com/otsi/retail/userStore/controller/StoreController.java
- user-store-mapping/src/main/java/com/otsi/retail/userStore/controller/UserController.java
- user-store-mapping/src/main/java/com/otsi/retail/userStore/exceptions/CustomExceptionHandler.java
- user-store-mapping/src/main/java/com/otsi/retail/userStore/service/StoreServiceImp.java
- user-store-mapping/src/main/java/com/otsi/retail/userStore/service/UserServiceImp.java
> added log messages

- new-sale-api/src/main/java/com/otsi/retail/newSale/controller/NewSaleController.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleServiceImpl.java
> some code changes made in list of deliverySlips,listOfSaleBils

- customer-management/src/main/java/com/otsi/retail/customerManagement/mapper/ReturnSlipMapper.java
- customer-management/src/main/java/com/otsi/retail/customerManagement/model/ReturnSlip.java
- customer-management/src/main/java/com/otsi/retail/customerManagement/service/CustomerServiceImpl.java
- customer-management/src/main/java/com/otsi/retail/customerManagement/vo/ListOfReturnSlipsVo.java
- customer-management/src/main/java/com/otsi/retail/customerManagement/vo/RetrnSlipDetailsVo.java
> some changes Done in returnslip

- customer-management/src/main/java/com/otsi/retail/customerManagement/config/Config.java
- customer-management/src/main/java/com/otsi/retail/customerManagement/service/CustomerServiceImpl.java
- customer-management/src/main/resources/application.properties
> some change done in customerserviceimpl

- debit-notes/src/main/java/com/otsi/retail/debitnotes/config/Config.java
- debit-notes/src/main/java/com/otsi/retail/debitnotes/gatewayresponse/GateWayResponse.java
- debit-notes/src/main/java/com/otsi/retail/debitnotes/vo/CustomerVo.java
> changed field in config class

- new-sale-api/src/main/java/com/otsi/retail/newSale/common/BillType.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/common/CommonRequestMappigs.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/config/Config.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/controller/NewSaleController.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/mapper/NewSaleMapper.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleService.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleServiceImpl.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/vo/BarcodeVo.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/vo/ListOfReturnSlipsVo.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/vo/ListOfSaleBillsVo.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/vo/NewSaleVo.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/vo/ReturnSummeryVo.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/vo/SaleReportVo.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/vo/SalesSummeryVo.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/vo/TaggedItems.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/vo/UserDetailsVo.java
- new-sale-api/src/main/resources/application.properties
> implemented SaleReport api

- customer-management/src/main/java/com/otsi/retail/customerManagement/service/CustomerServiceImpl.java
- customer-management/src/main/java/com/otsi/retail/customerManagement/vo/BarcodeVo.java
- customer-management/src/main/java/com/otsi/retail/customerManagement/vo/RetrnSlipDetailsVo.java
> some changes are done in returnslipDetails

- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleServiceImpl.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/vo/UserDetailsVo.java
> modified newsaleServiceImpl class

- new-sale-api/src/main/java/com/otsi/retail/newSale/controller/NewSaleController.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleService.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleServiceImpl.java
In this I changed save line item api from object to list.
> Change save line item request from object to list

- new-sale-api/src/main/java/com/otsi/retail/newSale/controller/NewSaleController.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/repository/DeliverySlipRepository.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/repository/LineItemReRepo.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleService.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleServiceImpl.java
Here I restricted the duplicate line items and DleliverySlips in order
> Restrict duplicate line items and DSSlips in order

- new-sale-api/src/main/java/com/otsi/retail/newSale/Entity/DeliverySlipEntity.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/Entity/LineItemsEntity.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/Entity/LineItemsReEntity.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/mapper/DeliverySlipMapper.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/mapper/NewSaleMapper.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleServiceImpl.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/vo/DeliverySlipVo.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/vo/LineItemVo.java
> modified code in new sale

- connection-pool/src/main/java/com/otsi/retail/connectionpool/common/CommonRequestMappigs.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/controller/PromotionController.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/repository/PromotionRepo.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/service/PromotionService.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/service/PromotionServiceImpl.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/vo/SearchPromotionsVo.java
- connection-pool/src/main/resources/application.yml
> Implemented Search Criteria for list of Promotions

- new-sale-api/src/main/java/com/otsi/retail/newSale/common/CommonRequestMappigs.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/controller/NewSaleController.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/mapper/NewSaleMapper.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleService.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleServiceImpl.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/vo/ClientDomains.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/vo/DeliverySlipVo.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/vo/UserDetailsVo.java
> modified dayClose Api

- new-sale-api/src/main/java/com/otsi/retail/newSale/config/Config.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleServiceImpl.java
- new-sale-api/src/main/resources/application.properties
Added inventory update from new sale
> Added inventory update from new sale

- customer-management/src/main/java/com/otsi/retail/customerManagement/service/CustomerServiceImpl.java
- customer-management/src/main/java/com/otsi/retail/customerManagement/vo/LineItemVo.java
- customer-management/src/main/java/com/otsi/retail/customerManagement/vo/RetrnSlipDetailsVo.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/Entity/LineItemsEntity.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/Entity/LineItemsReEntity.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/mapper/NewSaleMapper.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleServiceImpl.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/vo/LineItemVo.java
> modified return slip Api

- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleServiceImpl.java
commenting inventory service rest call
> commenting inventory service rest call

- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleServiceImpl.java
- new-sale-api/src/main/resources/application.properties
> Modified saleReport Api

- new-sale-api/src/main/java/com/otsi/retail/newSale/vo/UserDetailsVo.java
> Changes In listOfSaleBills API

- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleServiceImpl.java
- new-sale-api/src/main/resources/application.yml
> Changes in new sale

- customer-management/src/main/java/com/otsi/retail/customerManagement/controller/CustomerController.java
- customer-management/src/main/java/com/otsi/retail/customerManagement/mapper/ReturnSlipMapper.java
- customer-management/src/main/java/com/otsi/retail/customerManagement/repo/ReturnSlipRepo.java
- customer-management/src/main/java/com/otsi/retail/customerManagement/service/CustomerService.java
- customer-management/src/main/java/com/otsi/retail/customerManagement/service/CustomerServiceImpl.java
- customer-management/src/main/java/com/otsi/retail/customerManagement/vo/ListOfReturnSlipsVo.java
> added deleleReturnSlip api

- new-sale-api/src/main/java/com/otsi/retail/newSale/Entity/NewSaleEntity.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/Entity/PaymentAmountType.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/common/OrderStatus.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/controller/NewSaleController.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleService.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleServiceImpl.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/vo/PaymentDetailsVo.java
Added payment related code in NewSaleServiceImpl.java
> Added payment related code in NewSaleServiceImpl.java

- new-sale-api/pom.xml
- new-sale-api/src/main/java/com/otsi/retail/newSale/config/Config.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/controller/NewSaleController.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleServiceImpl.java
- new-sale-api/src/main/resources/application.properties
- new-sale-api/src/main/resources/application.yml
Added RabbitMQ Configuration for update payments
> Added RabbitMQ Configuration for update payments

- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleService.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleServiceImpl.java
Add update inventory from newsale by rabbitMq
> Add update inventory from newsale by rabbitMq

- connection-pool/src/main/java/com/otsi/retail/connectionpool/entity/PoolEntity.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/mapper/PoolMapper.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/vo/ConnectionPoolVo.java
> Modifications in Add Pool method

- connection-pool/src/main/java/com/otsi/retail/connectionpool/controller/PoolController.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/controller/PromotionController.java
> Cross Origin annotation removed

- connection-pool/src/main/java/com/otsi/retail/connectionpool/entity/PoolEntity.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/entity/PromotionsEntity.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/mapper/PoolMapper.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/mapper/PromotionMapper.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/vo/ConnectionPoolVo.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/vo/PromotionsVo.java
> Domain id added

- new-sale-api/src/main/java/com/otsi/retail/newSale/controller/NewSaleController.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleServiceImpl.java
Changes made in Giftvoucher as per new DB
> Changes made in Giftvoucher as per new DB

- new-sale-api/src/main/resources/application.properties
> modifies property file

- new-sale-api/src/main/java/com/otsi/retail/newSale/controller/NewSaleController.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/repository/PaymentAmountTypeRepository.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleService.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleServiceImpl.java
Added payment related API for confirm payment status
> Added payment related API for confirm payment status

- connection-pool/src/main/java/com/otsi/retail/connectionpool/common/CommonRequestMappigs.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/controller/PoolController.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/repository/PoolRepo.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/service/PoolService.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/service/PoolServiceImpl.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/vo/SearchPoolVo.java
> Pool-Searching API implemented

- connection-pool/src/main/java/com/otsi/retail/connectionpool/controller/PoolController.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/controller/PromotionController.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/repository/PoolRepo.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/repository/PromotionRepo.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/service/PoolService.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/service/PoolServiceImpl.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/service/PromotionService.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/service/PromotionServiceImpl.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/vo/ConnectionPromoVo.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/vo/PoolVo.java
> Pools and Promotions are getting based on domainId implemented

- connection-pool/src/main/java/com/otsi/retail/connectionpool/controller/PoolController.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/service/PoolService.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/service/PoolServiceImpl.java
> Modifications in searchPool API

- connection-pool/src/main/java/com/otsi/retail/connectionpool/entity/PromotionsEntity.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/mapper/PromotionMapper.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/service/PromotionServiceImpl.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/vo/PromotionsVo.java
> Changes in PromotionMapStore API and domainId related issues solved

- new-sale-api/src/main/java/com/otsi/retail/newSale/Entity/DeliverySlipEntity.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/mapper/DeliverySlipMapper.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleServiceImpl.java
Changes made in new sale for customer id(userId)
> Changes made in new sale for customer id(userId)

- new-sale-api/src/main/java/com/otsi/retail/newSale/vo/UserDetailsVo.java
> modified new sale Report

- new-sale-api/src/main/java/com/otsi/retail/newSale/Entity/LineItemsEntity.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleServiceImpl.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/vo/InventoryUpdateVo.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/vo/LineItemVo.java
> Added hsncodes in lineitem

- customer-management/src/main/java/com/otsi/retail/customerManagement/vo/LineItemVo.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/repository/NewSaleRepository.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/vo/ListOfSaleBillsVo.java
> modified returnslipReport,newSaleReport

- connection-pool/src/main/java/com/otsi/retail/connectionpool/mapper/PromotionMapper.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/repository/PromotionRepo.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/service/PromotionServiceImpl.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/vo/PromotionsVo.java
> changes in searchPromotion API

- new-sale-api/src/main/java/com/otsi/retail/newSale/Entity/LineItemsEntity.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/controller/NewSaleController.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleServiceImpl.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/vo/DeliverySlipVo.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/vo/GiftVoucherVo.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/vo/InventoryUpdateVo.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/vo/LineItemVo.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/vo/NewSaleVo.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/vo/PaymentAmountTypeVo.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/vo/PaymentDetailsVo.java
> Added logs to new sale APIs

- connection-pool/src/main/java/com/otsi/retail/connectionpool/service/PromotionServiceImpl.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/vo/SearchPromotionsVo.java
> changes in SearchPromotions API

- new-sale-api/src/main/java/com/otsi/retail/newSale/controller/NewSaleController.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/mapper/NewSaleMapper.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleService.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleServiceImpl.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/vo/InventoryUpdateVo.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/vo/NewSaleVo.java
Added payment types in order transaction and implemented list of Gv API
> Added payment types in order transaction and implemented list of Gv API

- new-sale-api/src/main/java/com/otsi/retail/newSale/Entity/LoyalityPointsEntity.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/common/CommonRequestMappigs.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/controller/NewSaleController.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/mapper/NewSaleMapper.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/repository/LoyalityPointsRepo.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleService.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleServiceImpl.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/vo/LoyalityPointsVo.java
> Loyalty Points API implemented

- new-sale-api/src/main/java/com/otsi/retail/newSale/config/Config.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleServiceImpl.java
- new-sale-api/src/main/resources/application.properties
Added queue to update inventoryUpdateForTextile
> Added queue to update inventoryUpdateForTextile

- new-sale-api/src/main/java/com/otsi/retail/newSale/Entity/LoyalityPointsEntity.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/common/CommonRequestMappigs.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/controller/NewSaleController.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/mapper/NewSaleMapper.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/repository/LoyalityPointsRepo.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleService.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleServiceImpl.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/vo/LoyalityPointsVo.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/vo/SearchLoyaltyPointsVo.java
> Search Loyalty Points API implemented

- connection-pool/src/main/java/com/otsi/retail/connectionpool/entity/PromotionsEntity.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/mapper/PromotionMapper.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/repository/PromotionRepo.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/service/PromotionServiceImpl.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/vo/PromotionsVo.java
> changes in clonePromotionByStore, searchPromotions APIs

- new-sale-api/src/main/java/com/otsi/retail/newSale/controller/NewSaleController.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/repository/GiftVoucherRepo.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleService.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleServiceImpl.java
Implemented Get Gv by userId APi
> Implemented Get Gv by userId

- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleServiceImpl.java
Chnages made in Create Deliveery slip
> Chnages made in Create Deliveery slip

- connection-pool/src/main/java/com/otsi/retail/connectionpool/common/BenfitType.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/common/CommonRequestMappigs.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/common/DiscountType.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/common/PercentageDiscountOn.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/common/PromotionStatus.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/controller/PromotionController.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/entity/BenfitEntity.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/entity/PromotionsEntity.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/mapper/PromotionMapper.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/repository/BenfitRepo.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/repository/PromotionRepo.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/service/PromotionService.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/service/PromotionServiceImpl.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/vo/BenfitVo.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/vo/PromotionsVo.java
> Add Benefit functionality implemented

- connection-pool/pom.xml
- connection-pool/src/main/java/com/otsi/retail/connectionpool/controller/PoolController.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/controller/PromotionController.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/entity/BenfitEntity.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/entity/PromotionsEntity.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/service/PoolServiceImpl.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/service/PromotionServiceImpl.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/vo/BenfitVo.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/vo/PromotionsVo.java
> Log4j Vulnerabilities issue Resolved

- connection-pool/src/main/java/com/otsi/retail/connectionpool/exceptions/CustomExceptionHandler.java
- connection-pool/src/main/resources/application-cloud.yml
- connection-pool/src/main/resources/application-common.yml
> Profiles implemented

- customer-management/pom.xml
- customer-management/src/main/java/com/otsi/retail/customerManagement/controller/CustomerController.java
- customer-management/src/main/java/com/otsi/retail/customerManagement/controller/ReasonController.java
- customer-management/src/main/java/com/otsi/retail/customerManagement/exceptions/CustomExceptionHandler.java
- customer-management/src/main/java/com/otsi/retail/customerManagement/service/CustomerServiceImpl.java
- customer-management/src/main/java/com/otsi/retail/customerManagement/service/ReasonServiceImpl.java
- customer-management/src/main/resources/application-cloud.yml
- customer-management/src/main/resources/application-common.yml
> profiles and log4j implemented

- new-sale-api/src/main/java/com/otsi/retail/newSale/Entity/GiftVoucherEntity.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/Entity/NewSaleEntity.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/common/NoteType.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/controller/NewSaleController.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/repository/GiftVoucherRepo.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleService.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleServiceImpl.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/vo/GiftVoucherVo.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/vo/NewSaleVo.java
Added Giftvoucher related APis
> Added Giftvoucher related APis

- connection-pool/src/main/java/com/otsi/retail/connectionpool/common/CommonRequestMappigs.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/controller/PromotionController.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/service/PromotionService.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/service/PromotionServiceImpl.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/vo/ReportVo.java
> implemented activevsInactive promo api

- new-sale-api/src/main/java/com/otsi/retail/newSale/controller/ReportsController.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/mapper/NewSaleMapper.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/ReportService.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/ReportsServiceImp.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/vo/ReportVo.java
> immplemented report dashboard apis

- new-sale-api/src/main/java/com/otsi/retail/newSale/repository/NewSaleRepository.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleServiceImpl.java
> added search conditions for saleSummeryReport

- new-sale-api/src/main/java/com/otsi/retail/newSale/config/Config.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/controller/ReportsController.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/ReportService.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/ReportsServiceImp.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/vo/ListOfReturnSlipsVo.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/vo/ReportVo.java
- new-sale-api/src/main/resources/application.properties
> implemented salesummery graph api

- promo-exchange/pom.xml
- promo-exchange/src/main/java/com/otsi/retail/promoexchange/controller/PromoExchangeController.java
- promo-exchange/src/main/java/com/otsi/retail/promoexchange/exceptions/CustomExceptionHandler.java
- promo-exchange/src/main/java/com/otsi/retail/promoexchange/service/CustomerServiceImpl.java
- promo-exchange/src/main/java/com/otsi/retail/promoexchange/service/PromoExchangeServiceeImpl.java
- promo-exchange/src/main/resources/application-cloud.yml
- promo-exchange/src/main/resources/application-common.yml
> Profiles and Log4j2 implemented

- connection-pool/src/main/java/com/otsi/retail/connectionpool/controller/PromotionController.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/entity/BenfitEntity.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/entity/PromotionsEntity.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/mapper/PromotionMapper.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/service/PromotionServiceImpl.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/vo/BenfitVo.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/vo/PromotionsVo.java
> Promotions API's

- connection-pool/src/main/java/com/otsi/retail/connectionpool/service/PromotionServiceImpl.java
> Promotions Clone Changes

- connection-pool/src/main/java/com/otsi/retail/connectionpool/common/ItemValue.java
> Promotions Item Value

- connection-pool/src/main/java/com/otsi/retail/connectionpool/entity/BenfitEntity.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/mapper/PromotionMapper.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/service/PromotionServiceImpl.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/vo/BenfitVo.java
> Slabs added for Benfit

- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleServiceImpl.java
Added condition to avoid error in Rabbit Listener method
> Added condition to avoid error in Rabbit Listener method

- new-sale-api/src/main/java/com/otsi/retail/newSale/controller/NewSaleController.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/repository/DeliverySlipRepository.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/repository/LineItemReRepo.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/repository/LineItemRepo.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleService.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleServiceImpl.java
kindly review and merge the code
> modified deliveryslipReport

- connection-pool/src/main/java/com/otsi/retail/connectionpool/service/PromotionServiceImpl.java
> Clone promotion changes

- new-sale-api/src/main/java/com/otsi/retail/newSale/Entity/LineItemsEntity.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/Entity/LineItemsReEntity.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleServiceImpl.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/vo/LineItemVo.java
Added cgst and Sgst fields in Line Items
> Added cgst and Sgst fields in Line Items

- new-sale-api/src/main/resources/application-cloud.yml
- new-sale-api/src/main/resources/application-common.yml
- new-sale-api/src/main/resources/application.properties
- new-sale-api/src/main/resources/application.yml
Changed YAML file for RabbitMq Config
> Changed YAML file for RabbitMq Config

- new-sale-api/src/main/java/com/otsi/retail/newSale/controller/ReportsController.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/ReportService.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/ReportsServiceImp.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/vo/ReportVo.java
please kindly review and merge the code
> added some graph Api's

- new-sale-api/src/main/java/com/otsi/retail/newSale/config/Config.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleServiceImpl.java
- new-sale-api/src/main/resources/application.properties
Added inventory update for Retail domain
> Added inventory update for Retail domain

- new-sale-api/src/main/java/com/otsi/retail/newSale/Entity/DeliverySlipEntity.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/Entity/LineItemsEntity.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/Entity/LineItemsReEntity.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/mapper/DeliverySlipMapper.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleServiceImpl.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/vo/DeliverySlipVo.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/vo/LineItemVo.java
> storeIds added in lineItems,lineItemsRe and DeliverySlips

- new-sale-api/src/main/java/com/otsi/retail/newSale/controller/ReportsController.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/repository/DeliverySlipRepository.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/repository/LineItemReRepo.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/ReportService.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/ReportsServiceImp.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/vo/ReportVo.java
kindly review and merge the code
> added Top5salesByRepresentative api

- new-sale-api/src/main/java/com/otsi/retail/newSale/controller/ReportsController.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/repository/NewSaleRepository.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/ReportService.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/ReportsServiceImp.java
kindly Review and merge the code
> added storeId's for all Graph apis

- new-sale-api/src/main/java/com/otsi/retail/newSale/Entity/PaymentAmountType.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/common/PaymentType.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/config/Config.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/repository/PaymentAmountTypeRepository.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleServiceImpl.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/vo/InventoryUpdateVo.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/vo/PaymentAmountTypeVo.java
- new-sale-api/src/main/resources/application.properties
> rabbitMQ issue solved and giftVoucherId added

- new-sale-api/src/main/java/com/otsi/retail/newSale/mapper/NewSaleMapper.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/repository/DeliverySlipRepository.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/repository/LineItemRepo.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/repository/NewSaleRepository.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleServiceImpl.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/vo/ListOfDeliverySlipVo.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/vo/ListOfSaleBillsVo.java
Kindly Review  and merge the code
> added storeId for all the reports

- customer-management/pom.xml
- customer-management/src/main/java/com/otsi/retail/customerManagement/controller/CustomerController.java
- customer-management/src/main/resources/application.properties
- customer-management/src/main/resources/application.yml
> Circuit-Breaker Implemented

- connection-pool/src/main/java/com/otsi/retail/connectionpool/entity/RuleEntity.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/service/PoolServiceImpl.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/service/PromotionService.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/service/PromotionServiceImpl.java
- connection-pool/src/main/java/com/otsi/retail/connectionpool/vo/RuleVo.java
> changes in Rules

- new-sale-api/src/main/java/com/otsi/retail/newSale/config/Config.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/controller/NewSaleController.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleService.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleServiceImpl.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/vo/UpdateCreditRequest.java
- new-sale-api/src/main/resources/application.properties
> Credit Notes Functionality Implemented

- new-sale-api/src/main/java/com/otsi/retail/newSale/Entity/LineItemsEntity.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/Entity/LineItemsReEntity.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/service/NewSaleServiceImpl.java
- new-sale-api/src/main/java/com/otsi/retail/newSale/vo/LineItemVo.java
> Added fields in lineItem Table(Tex,Re) Table and Debit notes implemented
